"""Änderung der Spaltennamen für Transaction

Revision ID: f31dabe3288a
Revises: 
Create Date: 2025-01-24 12:31:50.716259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31dabe3288a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_transaction_user_id', 'user', ['user_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_user_id', type_='foreignkey')

        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
